Patch 1
hashicorp/consul-k8s pull request #1380
Opened 2022-07-28 11:26 UTC by s-andresen

Changes proposed in this PR:
Added extraLabels to connectInject and serverACLInit in values.yaml so if declared in the values file then these additional labels will be added to the pods

How I've tested this PR:
Tested the helm chart on my kubernetes cluster with and without declaring the extraLabels to ensure everything works as expected.

How I expect reviewers to test this PR:
Same as how I tested

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

2022-07-28 11:26 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=1380)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=1380)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul-k8s?pullRequest=1380).</sub>

2022-08-15 20:28 UTC, david-yu commented
@s-andresen Could you tell us whether you expect to apply the same labels for both components? We had a similar PR previously but opted for an approach to create a label for all components for a global label instead.

2022-08-18 15:21 UTC, lkysow requested changes
Looking good, but can you please add bats tests? You should be able to follow the pattern for other `extraLabels` tests.

2022-08-18 15:21 UTC, lkysow commented on charts/consul/values.yaml
> +serverACLInit:
Let's put this under `global.acls.serverACLInit`?

2022-11-12 18:24 UTC, david-yu commented
Closing in favor of https://github.com/hashicorp/consul-k8s/pull/1678, could you open a separate PR That enables ServerACLInit with bats test included?

2022-11-12 18:24 UTC, closed without merging