Upgrade to go1.19.2
hashicorp/consul-k8s pull request #1633
Opened 2022-10-19 14:42 UTC by analogue

Context: [NET-240](https://hashicorp.atlassian.net/browse/NET-240)

Changes proposed in this PR:
- Upgrade to go 1.19.2
- Upgrade to gotestsum 1.8.2

How I've tested this PR:
TBD

How I expect reviewers to test this PR:
TBD

2022-10-19 16:05 UTC, analogue commented on .circleci/config.yml
> +      - image: docker.mirror.hashicorp.services/hashicorpdev/consul-helm-test:0.15.0
Nice catch!

2022-10-19 16:13 UTC, jmurret requested changes
can you add a changelog entry and please leave that reminder from the PR template in your PR?  The changelog should be similar to this: https://github.com/hashicorp/consul-k8s/pull/1292/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR2-R7

2022-10-19 16:18 UTC, jmurret commented
also, this is missing the following files, which means you need to run `go mod tidy` in each of these directories after you modify `go.mod`.
- acceptance/go.sum
- cli/go.sum
- control-plane/go.sum

For reference, I am auditing your PR against the two PRs linked in the JIRA ticket.

2022-10-19 16:23 UTC, jmurret commented on .circleci/config.yml
> +            wget https://github.com/gotestyourself/gotestsum/releases/download/v1.8.2/gotestsum_1.8.2_linux_amd64.tar.gz
👏 🎉 🙏 nice!

2022-10-19 18:34 UTC, analogue commented
> also, this is missing the following files, which means you need to run `go mod tidy` in each of these directories after you modify `go.mod`.
> 
>     * acceptance/go.sum
> 
>     * cli/go.sum
> 
>     * control-plane/go.sum
> 
> 
> For reference, I am auditing your PR against the two PRs linked in the JIRA ticket. I think this and the changelog entry are the missing items.

I re-ran `go mod tidy` on those files, but it didn't yield any changes.

2022-10-19 19:07 UTC, jmurret approved these changes
👍 ❤️ :shipit:

2022-10-20 15:10 UTC, t-eckert approved these changes
Great work!

2022-10-20 21:27 UTC, merged