Enable envoy bootstrap config logging if global.logLevel == debug
hashicorp/consul-k8s pull request #1910
Opened 2023-02-14 21:11 UTC by kyhavlov

Changes proposed in this PR:
- Enable the Envoy bootstrap config logging flag added in https://github.com/hashicorp/consul/pull/15988 when `global.logLevel` is `debug`.

How I've tested this PR:
Unit tests

How I expect reviewers to test this PR:
CI/Unit tests

Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

2023-02-14 21:32 UTC, david-yu commented
@kyhavlov Will there also be a PR for main and 1.0.x? Btw we have a `backport/1.0.x` and `backport/0.49.x` label that does automatic back ports for you now.

2023-02-14 21:34 UTC, thisisnotashwin commented
> @kyhavlov Will there also be a PR for main and 1.0.x? Btw we have a `backport/1.0.x` and `backport/0.49.x` label that does automatic back ports for you now.

@david-yu They don't use `consul connect envoy` and use the dataplane. the dataplane is already configured with the correct behavior.

2023-02-14 21:35 UTC, david-yu commented
Ahh ok thank you!

2023-02-15 15:09 UTC, thisisnotashwin approved these changes
excellent work!!

2023-02-15 15:12 UTC, thisisnotashwin requested changes
I checked CI and it looks like we shouldn't assert `-enable-config-gen-logging` in the prestop hooks for any of the gateways.

2023-02-15 15:12 UTC, thisisnotashwin commented on charts/consul/test/unit/ingress-gateways-deployment.bats
> +}
Do these get configured for the preStop command as well? i think we can remove the preStop assertions from all the BATS tests.

2023-02-23 18:44 UTC, kyhavlov commented
Yes it's ready for review again, although I'm not sure why the mesh gateway test is failing - it was passing before and I didn't change it

2023-02-24 18:12 UTC, thisisnotashwin approved these changes
excellent work here!!

2023-02-24 18:12 UTC, merged