Manual backport of Improvement- Added helm inputs for managing audit logs into release/1.0.x
hashicorp/consul-k8s pull request #2368
Opened 2023-06-14 04:27 UTC by Ganeshrockz

## Backport

This PR is manually created from #2265 to be assessed for backporting targeting the release/1.0.x

The below text is copied from the body of the original PR.

---

Changes proposed in this PR:
- Adds the relevant inputs in values.yaml to configure audit logging in Consul enterprise.
- Behind the scenes, values get translated to the json configuration present [here](https://developer.hashicorp.com/consul/docs/agent/config/config-files#audit) and the whole configuration is added as a file in the Consul server's config map.

How I've tested this PR:
- Unit tests
- CI

How I expect reviewers to test this PR:
- I've added the `auditLog` field under `server`. Should the same be added to `client`?

Checklist:
- [X] Tests added
- [X] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

---

2023-06-16 17:41 UTC, david-yu commented
This might be related to pipeline issues that @wilkermichael raised on Slack, the same for the 0.49.x PR could be said.

2023-06-20 19:21 UTC, david-yu commented
Could you re-based this PR and try running tests again?

2023-06-21 17:37 UTC, curtbushko requested changes

2023-06-21 17:37 UTC, curtbushko commented on .changelog/2368.txt
> +```release-note:improvement
Same as the other backport, this should use the original PR .changelog/2265.txt

2023-06-22 15:23 UTC, curtbushko approved these changes

2023-06-23 04:01 UTC, curtbushko commented
See: https://github.com/hashicorp/consul-k8s/pull/2434

2023-06-23 16:08 UTC, david-yu commented
@curtbushko Could you merge if all looks good?

2023-06-23 16:11 UTC, merged