feature: adding security context and annotations to tls and acl init/cleanup jobs
hashicorp/consul-k8s pull request #2508
Opened 2023-07-03 20:29 UTC by Chinikins

Changes proposed in this PR:
- Ability to add annotations to acl init and cleanup jobs
- Ability to add annotations to tls init and cleanup jobs
- Ability to add pod security context to acl init and cleanup jobs
- Ability to add pod security context to acl init and cleanup jobs

How I've tested this PR:

Ran unit tests, helm lint, and also used changes to deploy at work where jobs not having the security context set by default run into regulation issues.

How I expect reviewers to test this PR:

helm lint and unit tests

Checklist:
- [x] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

2023-07-03 20:29 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=2508)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=2508)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**chini mukhopadhyay** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul-k8s?pullRequest=2508).</sub>

2023-07-06 23:35 UTC, david-yu commented
Thanks this sounds like a good change. Could you tell us more why you would need annotations on acl init and tls init jobs?

2023-07-07 13:53 UTC, Chinikins commented
Sure, it's for flexibility more than anything else - in our case we have istio running on the cluster as well and using consul for just kv purposes, so adding annotations to the jobs to tell istio to ignore sidecar injection into these jobs please. But I can think of a lot of use cases where folks might need to add annotations to a pod depending on what else is on the cluster/use cases. A fairly simple one would be if you have a cluster autoscaler and you're doing an upgrade, annotating the job to also be skipped by the cluster autoscaler.

2023-07-07 19:11 UTC, DanStough requested changes
Thank you so much for the PR @Chinikins 🥳 🎉 !

A couple of things to address in the PR before I think we are ready to merge:
1. See the comment about the indent for `containerSecurityContext` 
2. Can we add some unit tests for the annotation fields you added? I believe there is some [prior art here](https://github.com/hashicorp/consul-k8s/blob/1161322e494509ca2642811d88c92b898bb7a4d4/charts/consul/test/unit/server-statefulset.bats#L622-L643).
3. It looks like `.Values.global.acls.nodeSelector` is re-used in the following files. IMHO we should add `.Values.global.acls.annotations` to them as well, along with the respective unit tests.
    1. `gateway-cleanup-job.yaml`
    2. `gateway-resource-job.yaml`

2023-07-07 21:00 UTC, Chinikins commented
thank you for the quick review @DanStough !

2023-07-07 21:47 UTC, DanStough requested changes
Two copy-pasta typos and then we're good to go!

2023-07-07 21:47 UTC, DanStough commented on charts/consul/test/unit/server-acl-init-job.bats
> +      -s templates/server-acl-init-cleanup-job.yaml \
```suggestion
      -s templates/server-acl-init-job.yaml \
```

2023-07-07 21:47 UTC, DanStough commented on charts/consul/test/unit/server-acl-init-job.bats
> +      -s templates/server-acl-init-cleanup-job.yaml \
```suggestion
      -s templates/server-acl-init-job.yaml \
```

2023-07-07 21:54 UTC, DanStough approved these changes

2023-07-10 15:55 UTC, closed without merging

2023-07-10 18:30 UTC, Chinikins commented
Is there a way to have the CI tests run in the future that is more friendly to outside commits? It's a bit discouraging to continue contributions in this odd manner. :/

2023-07-10 18:40 UTC, DanStough commented
I understand and apologize for the inconvenience. It's an open item for us to find a better solution. We recently migrated chunks of our CI to GH actions and still need to sort out the workflows for forks. 

Thank you again for the PR!

2023-07-10 21:01 UTC, david-yu commented
@Chinikins I'll need to follow up with Github to see how they can help us make this easier. Our CI workflow is a bit unique here on consul-k8s so may need some assistance from them.