correct prometheus port and scheme annotations if tls is enabled
hashicorp/consul-k8s pull request #2782
Opened 2023-08-16 13:55 UTC by rigalGit

Changes proposed in this PR:
Fixing #1856 
- Correct prometheus port ( 8501) and scheme ( https) annotations if tls is enabled.
- Setting prometheus scheme to http if tls is disabled. 

How I've tested this PR:
Created a local cluster using kind and checked prometheus annotations on consul-server  pod using kubectl.

kubectl get pod consul-server-0 --namespace consul -o jsonpath='{.metadata.annotations}'

How I expect reviewers to test this PR:

Checklist:
- [ ] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-08-16 19:17 UTC, david-yu commented
Thanks @rigalGit I assume you are looking to fix this issue? https://github.com/hashicorp/consul-k8s/issues/1856

2023-08-17 04:43 UTC, rigalGit commented
> Thanks @rigalGit I assume you are looking to fix this issue? #1856

yes [david-yu](https://github.com/david-yu)

2023-08-17 05:00 UTC, Ganeshrockz requested changes
Can you add bats unit tests for this change [here](https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/test/unit/server-config-configmap.bats)?

2023-08-17 05:19 UTC, david-yu commented
Could you also test to see if this works correctly when both metrics merging enabled and ACLs enabled as called out in that issue #1856

2023-08-24 14:42 UTC, thisisnotashwin commented
@rigalGit any chance you can make that changes requested and we can review it and merge it after?

2023-08-26 01:11 UTC, huikang commented
Tested it manually and it works for me.

2023-08-29 03:40 UTC, rigalGit commented
> Can you add bats unit tests for this change [here](https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/test/unit/server-config-configmap.bats)?

added

2023-08-29 03:41 UTC, rigalGit commented
> @rigalGit any chance you can make that changes requested and we can review it and merge it after?

addressed

2023-08-29 05:56 UTC, Ganeshrockz approved these changes

2023-08-29 12:08 UTC, huikang approved these changes

2023-08-29 12:54 UTC, merged