Mw/net 5679 explicit upstreams mesh webhook injects upstream env variable
hashicorp/consul-k8s pull request #2995
Opened 2023-09-21 20:54 UTC by wilkermichael

Changes proposed in this PR:
- This introduces injection of the port/ip address environment variables

How I've tested this PR:
- unit tests

How I expect reviewers to test this PR:
👀 

Checklist:
- [x] Tests added
- [ ] [CHANGELOG entry added](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-09-22 20:01 UTC, DanStough requested changes
Looks great! My only dealbreaker was the naming of the ENV variable. Open to discussion, though.

2023-09-22 20:24 UTC, wilkermichael commented on control-plane/connect-inject/common/annotation_processor.go
> +}
oh yeah, I'll fix this after Iryna merges her changes in

2023-09-22 20:25 UTC, wilkermichael commented on control-plane/connect-inject/constants/constants_test.go
> +func TestGetDefaultConsulNamespace(t *testing.T) {
ah thanks, good catch

2023-09-22 20:37 UTC, DanStough commented on control-plane/connect-inject/webhook_v2/container_env.go
> +			Name:  fmt.Sprintf("%s_%s_CONNECT_SERVICE_HOST", serviceName, portName),
My bad, the RFC is just like how you have it :homer-disappear:

2023-09-22 20:43 UTC, wilkermichael commented on control-plane/connect-inject/webhook_v2/container_env.go
> +	upstreams, err := common.ProcessPodUpstreams(pod, true, true)
it doesn't have enablePartitions, and also honestly it doesn't really matter for this usecase. We don't care about the partition/namespace values (they're optional anyways if they're enabled) so we can just enable it always.

2023-09-23 05:33 UTC, wilkermichael commented
@DanStough can you take a look at this now that I've addressed your comments? Thanks!

2023-09-25 15:25 UTC, thisisnotashwin approved these changes

2023-09-25 15:46 UTC, DanStough approved these changes

2023-09-25 15:56 UTC, merged