uniform make file experience
hashicorp/consul-k8s pull request #3198
Opened 2023-11-10 01:14 UTC by wangxinyi7

Make the makefile experience uniform
Changes proposed in this PR:
- introduce help target to display help info for each of targets

Checklist:
- [ ] ~Tests added~
- [ ] [~CHANGELOG entry added~](https://github.com/hashicorp/consul-k8s/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-11-21 18:26 UTC, curtbushko requested changes
Looks pretty good.  Just a small request.

2023-11-21 20:31 UTC, wangxinyi7 commented on Makefile
Yup, updated @curtbushko

2023-11-22 15:31 UTC, curtbushko approved these changes
Thanks!

2023-11-22 15:36 UTC, curtbushko commented
@wangxinyi7 You'll want to backport these changes to all the release/1.1.x and up branches

2023-11-23 17:21 UTC, wangxinyi7 commented
@curtbushko Thanks for approving, just double check for the backport, I see there are backport labels of `1.1.x` `1.2.x` `1.3.x` in the dropdown menu, I need to select them and the following steps (open PR, approval and merging) will all be kicked off automatically right?

2023-11-23 17:55 UTC, curtbushko commented
@wangxinyi7 Yes, those are the versions and it used the same backport assistant that the Consul repo uses. I recommend squashing all of our commits down to 1 commit before merging because the backport assistant has troubles sometimes and I find that it helps it get less confused...

2023-11-23 17:58 UTC, wangxinyi7 commented
Thanks for your info! @curtbushko

2023-11-23 18:00 UTC, merged