remove catalogv2 implementation and tests
hashicorp/consul-k8s pull request #4061
Opened 2024-05-30 20:51 UTC by rboyer

### Changes proposed in this PR ###  

- Remove all direct plumbing related to the `resource-apis` and `v2tenancy` experiments
- Remove all remaining dead code pertaining to the remainder of Consul resources _(all experimental)_
- Remove all tests of the above

https://hashicorp.atlassian.net/browse/NET-9089

2024-06-04 18:14 UTC, rboyer commented
Pretty sure now I have had all of the flavors of acceptance test pass at least once, so I probably didn't over-delete anything this time.

2024-06-04 18:14 UTC, rboyer commented on Makefile
> +ifeq ("$(GOTESTSUM_PATH)","")
I cribbed this conditional gotestsum running approach from the consul main repo to help when I was running and re-running the normal tests.

2024-06-06 15:22 UTC, DanStough requested changes
My only blocking comment is deleting the rest of the v2 Namespace controller that uses the V1 APIs.

2024-06-06 16:27 UTC, DanStough approved these changes
:shipit: 🚀

2024-06-18 19:59 UTC, merged

2024-10-18 03:22 UTC, zalimeni commented
Removing labels for now but wondering whether we should backport this change to 1.4-1.6 to avoid discrepancies in backports.