Add custom annotations support for catalog sync and connectInject pods via Helm
hashicorp/consul-k8s pull request #775
Opened 2021-10-11 03:10 UTC by jeanmorais

Changes proposed in this PR:
- Add custom annotations support for catalog sync and connectInject pods via Helm.

How I've tested this PR:
- Unit tests

Fixes #760

How I expect reviewers to test this PR:
* `bats sync-catalog-deployment.bats`
* `bats connect-inject-deployment.bats`

Checklist:
- [x] Tests added
- [ ] CHANGELOG entry added 
  > HashiCorp engineers only, community PRs should not add a changelog entry.
  > Entries should use present tense (e.g. Add support for...)

2022-03-12 17:38 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=775)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/consul-k8s?pullRequest=775)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**0** out of **2** committers have signed the CLA.


- [ ] david-yu
- [ ] jeanmorais

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/consul-k8s?pullRequest=775).</sub>

2022-06-27 16:48 UTC, lkysow requested changes
LGTM but I think there are some `{-end}`'s being deleted incorrectly

2022-06-27 16:48 UTC, lkysow commented on charts/consul/templates/connect-inject-deployment.yaml
> -        {{- end }}
why is this being removed?

2022-06-27 16:48 UTC, lkysow commented on charts/consul/templates/sync-catalog-deployment.yaml
> -        {{- end }}
same here

2022-06-29 03:43 UTC, jeanmorais commented on charts/consul/templates/connect-inject-deployment.yaml
> -        {{- end }}
It went unnoticed. Fixed.

2022-06-29 03:43 UTC, jeanmorais commented on charts/consul/templates/sync-catalog-deployment.yaml
> -        {{- end }}
fixed

2022-06-29 16:45 UTC, lkysow approved these changes
Thank you so much!

2022-06-29 16:45 UTC, merged